"""Install chargate's git hooks globally via the pre-commit framework.

This is the subprocess/filesystem boundary for ``chargate install-hooks`` —
everything that shells out (``pre-commit``, ``git config --global``) or touches
``$HOME`` lives here so the rest of the package stays pure and unit-testable
(mirroring :mod:`chargate.git`). The runner, tool-presence probe and home
directory are injectable so the wiring logic is tested without mutating the real
global git config or the developer's ``$HOME``.

What "global" means here: ``pre-commit init-templatedir`` generates the dispatcher
scripts into ``<template>/hooks``; we patch each to read the *global*
``~/.pre-commit-config.yaml`` (init-templatedir hardcodes a per-repo config path,
which would make the hooks no-op in repos without their own config), then point
``core.hooksPath`` at that dir so the hooks apply to *every existing repo
immediately* and set ``init.templateDir`` so fresh clones inherit them too.

The managed config carries chargate's own hooks inside a ``>>> chargate-managed >>>``
block that is regenerated on every run; anything you add *outside* that block (your
own repos/hooks) is preserved across reruns.

Two independent delivery paths, by design: the ``chargate`` CLI ships via Homebrew,
while the hook *scripts* (``hooks/*.sh``) are fetched by pre-commit from the chargate
repo at the pinned ``rev`` — they are not in the installed wheel.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from collections.abc import Callable
from pathlib import Path

from chargate import __version__

Runner = Callable[[list[str]], "subprocess.CompletedProcess[str]"]
Which = Callable[[str], str | None]

# First line of a chargate-managed ~/.pre-commit-config.yaml. We only ever
# overwrite a config that carries this marker (or when --force is given), so a
# hand-maintained config is never silently clobbered.
SENTINEL = "# managed-by: chargate install-hooks"

# Markers around the chargate-owned repos in the managed config. Only the lines
# between them are regenerated; anything the user adds outside is preserved.
_MANAGED_START = "  # >>> chargate-managed (regenerated; edits here are overwritten) >>>"
_MANAGED_END = "  # <<< chargate-managed <<<"

# Hook stages we install dispatchers for. commit-msg lets users wire message hooks
# (e.g. a commit-message linter) in their preserved section.
_HOOK_TYPES = ("pre-commit", "pre-push", "commit-msg")

# init-templatedir hardcodes this per-repo config path into each dispatcher.
_PER_REPO_CONFIG = "--config=.pre-commit-config.yaml"

# git config keys we own.
_HOOKS_PATH_KEY = "core.hooksPath"
_TEMPLATE_DIR_KEY = "init.templateDir"

# git config --unset exits 5 when the key is absent; that is a no-op for us.
_GIT_CONFIG_UNSET_MISSING = 5


class HookInstallError(RuntimeError):
    """A hook (un)install step failed; the message is user-actionable."""


def _default_runner(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, check=False)


def _managed_block(rev: str) -> str:
    """The chargate-owned, marker-delimited region of the config."""
    return (
        f"{_MANAGED_START}\n"
        "  - repo: https://github.com/MagmaMoose/chargate\n"
        f"    rev: {rev}\n"
        "    hooks:\n"
        "      - id: actions-pin-sha\n"
        "      - id: conventional-branch-name\n"
        f"{_MANAGED_END}\n"
    )


def _full_config(rev: str) -> str:
    """A complete managed config (used for a fresh or force-overwritten file)."""
    return (
        f"{SENTINEL}\n"
        "# The block between the >>> / <<< markers is regenerated by `chargate\n"
        "# install-hooks` (rerun to refresh, `chargate uninstall-hooks` to remove).\n"
        "# Anything OUTSIDE that block — your own repos/hooks — is preserved across reruns.\n"
        "default_install_hook_types: [pre-commit, pre-push, commit-msg]\n"
        "repos:\n"
        f"{_managed_block(rev)}"
    )


def _render_config(existing: str | None, rev: str) -> str:
    """Regenerate only the chargate-managed block, preserving user-added content."""
    if existing and _MANAGED_START in existing and _MANAGED_END in existing:
        lines = existing.splitlines()
        start = next(i for i, ln in enumerate(lines) if ln.strip() == _MANAGED_START.strip())
        end = next(i for i, ln in enumerate(lines) if ln.strip() == _MANAGED_END.strip())
        block = _managed_block(rev).splitlines()
        return "\n".join(lines[:start] + block + lines[end + 1 :]) + "\n"
    return _full_config(rev)


def _point_dispatchers_at_global_config(paths: _Paths) -> None:
    """Repoint the generated dispatchers from the per-repo config to the global one.

    ``pre-commit init-templatedir`` bakes ``--config=.pre-commit-config.yaml`` into
    each dispatcher, so without this the hooks would no-op in any repo lacking its
    own config. We rewrite that to the absolute managed-config path.
    """
    replacement = f"--config={paths.config}"
    for hook_type in _HOOK_TYPES:
        dispatcher = paths.hooks_dir / hook_type
        if not dispatcher.exists():
            continue
        text = dispatcher.read_text(encoding="utf-8")
        if _PER_REPO_CONFIG in text:
            dispatcher.write_text(text.replace(_PER_REPO_CONFIG, replacement), encoding="utf-8")


class _Paths:
    """Resolved on-disk locations, rooted at ``home`` for testability."""

    def __init__(self, home: Path) -> None:
        self.home = home
        self.config = home / ".pre-commit-config.yaml"
        self.state = home / ".config" / "chargate" / "state.json"
        self.template_dir = home / ".config" / "chargate" / "git-template"
        self.hooks_dir = self.template_dir / "hooks"


def _git_config_get(runner: Runner, key: str) -> str | None:
    proc = runner(["git", "config", "--global", "--get", key])
    if proc.returncode != 0:
        return None
    value = proc.stdout.strip()
    return value or None


def _git_config_set(runner: Runner, key: str, value: str) -> None:
    proc = runner(["git", "config", "--global", key, value])
    if proc.returncode != 0:
        raise HookInstallError(
            f"`git config --global {key} {value}` failed (exit {proc.returncode}): "
            f"{proc.stderr.strip()}"
        )


def _git_config_unset(runner: Runner, key: str) -> None:
    proc = runner(["git", "config", "--global", "--unset", key])
    if proc.returncode not in (0, _GIT_CONFIG_UNSET_MISSING):
        raise HookInstallError(
            f"`git config --global --unset {key}` failed (exit {proc.returncode}): "
            f"{proc.stderr.strip()}"
        )


def install_hooks(
    *,
    force: bool = False,
    home: Path | None = None,
    runner: Runner | None = None,
    which: Which | None = None,
) -> list[str]:
    """Wire chargate's hooks into git globally. Returns user-facing messages.

    Raises :class:`HookInstallError` for setup failures (missing ``pre-commit``,
    a foreign config that would be clobbered without ``force``, or a failing
    subprocess).
    """
    run: Runner = runner or _default_runner
    which_fn: Which = which or shutil.which
    paths = _Paths(home or Path.home())
    rev = f"v{__version__}"

    if which_fn("git") is None:
        raise HookInstallError("`git` is not on PATH; cannot configure global hooks.")
    if which_fn("pre-commit") is None:
        raise HookInstallError(
            "`pre-commit` is not on PATH. Install it first "
            "(`brew install pre-commit` or `pipx install pre-commit`), then rerun."
        )

    messages: list[str] = []

    # 1. Managed global config — never clobber a foreign one without --force; on a
    #    chargate-managed file, refresh only our block and keep the user's section.
    existing = paths.config.read_text(encoding="utf-8") if paths.config.exists() else None
    if existing is not None and SENTINEL not in existing and not force:
        raise HookInstallError(
            f"{paths.config} already exists and was not written by chargate. "
            "Refusing to overwrite it; rerun with --force to replace it."
        )
    preserved = existing is not None and _MANAGED_START in existing
    paths.config.write_text(_render_config(existing, rev), encoding="utf-8")
    messages.append(
        f"{'Refreshed' if preserved else 'Wrote'} managed pre-commit config: "
        f"{paths.config} (pinned {rev})"
    )

    # 2. Capture the genuine pre-chargate global config once, for uninstall restore.
    prior_hooks_path = _git_config_get(run, _HOOKS_PATH_KEY)
    prior_template_dir = _git_config_get(run, _TEMPLATE_DIR_KEY)
    if not paths.state.exists():
        paths.state.parent.mkdir(parents=True, exist_ok=True)
        paths.state.write_text(
            json.dumps(
                {_HOOKS_PATH_KEY: prior_hooks_path, _TEMPLATE_DIR_KEY: prior_template_dir},
                indent=2,
            ),
            encoding="utf-8",
        )

    # 3. Generate the framework dispatchers into <template>/hooks for each stage,
    #    then repoint them at the global managed config.
    paths.template_dir.mkdir(parents=True, exist_ok=True)
    hook_type_args: list[str] = []
    for hook_type in _HOOK_TYPES:
        hook_type_args += ["--hook-type", hook_type]
    proc = run(["pre-commit", "init-templatedir", str(paths.template_dir), *hook_type_args])
    if proc.returncode != 0:
        raise HookInstallError(
            f"`pre-commit init-templatedir` failed (exit {proc.returncode}): {proc.stderr.strip()}"
        )
    _point_dispatchers_at_global_config(paths)

    # 4. Make them active everywhere: hooksPath (retroactive) + templateDir (new clones).
    if prior_hooks_path and prior_hooks_path != str(paths.hooks_dir):
        messages.append(
            f"Repointing {_HOOKS_PATH_KEY}: {prior_hooks_path} -> {paths.hooks_dir}. "
            "Hooks at the old path are no longer active (this disables any non-chargate "
            "global hooks there). Run `chargate uninstall-hooks` to restore."
        )
    _git_config_set(run, _HOOKS_PATH_KEY, str(paths.hooks_dir))
    _git_config_set(run, _TEMPLATE_DIR_KEY, str(paths.template_dir))

    messages.append(
        "Global git hooks installed (pre-commit + pre-push + commit-msg) for all repositories."
    )
    return messages


def uninstall_hooks(
    *,
    home: Path | None = None,
    runner: Runner | None = None,
) -> list[str]:
    """Revert what :func:`install_hooks` set, touching only chargate-owned config."""
    run: Runner = runner or _default_runner
    paths = _Paths(home or Path.home())

    prior: dict[str, str | None] = {}
    if paths.state.exists():
        try:
            prior = json.loads(paths.state.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            prior = {}

    messages: list[str] = []
    _restore_or_unset(run, _HOOKS_PATH_KEY, str(paths.hooks_dir), prior, messages)
    _restore_or_unset(run, _TEMPLATE_DIR_KEY, str(paths.template_dir), prior, messages)

    # Remove the managed config only if it still carries our marker.
    if paths.config.exists() and SENTINEL in paths.config.read_text(encoding="utf-8"):
        paths.config.unlink()
        messages.append(f"Removed managed pre-commit config: {paths.config}")

    if paths.state.exists():
        paths.state.unlink()

    if not messages:
        messages.append("Nothing to uninstall (no chargate-managed global hooks found).")
    return messages


def _restore_or_unset(
    runner: Runner,
    key: str,
    managed_value: str,
    prior: dict[str, str | None],
    messages: list[str],
) -> None:
    """Revert ``key`` only if it currently holds chargate's managed value."""
    current = _git_config_get(runner, key)
    if current != managed_value:
        # Someone repointed it after us (or it was never ours) — leave it alone.
        return
    restored = prior.get(key)
    if restored:
        _git_config_set(runner, key, restored)
        messages.append(f"Restored {key}: {managed_value} -> {restored}")
    else:
        _git_config_unset(runner, key)
        messages.append(f"Unset {key} (was {managed_value})")
