"""Install chargate's git hooks globally via the pre-commit framework.

This is the subprocess/filesystem boundary for ``chargate install-hooks`` —
everything that shells out (``pre-commit``, ``git config --global``) or touches
``$HOME`` lives here so the rest of the package stays pure and unit-testable
(mirroring :mod:`chargate.git`). The runner, tool-presence probe and home
directory are injectable so the wiring logic is tested without mutating the real
global git config or the developer's ``$HOME``.

What "global" means here: ``pre-commit init-templatedir`` generates the dispatcher
scripts into ``<template>/hooks``; we then point ``core.hooksPath`` at that dir so
the hooks apply to *every existing repo immediately*, and set ``init.templateDir``
so freshly cloned/``git init``-ed repos inherit them too. The dispatchers read a
managed global ``~/.pre-commit-config.yaml`` that pins chargate's hooks.

Two independent delivery paths, by design: the ``chargate`` CLI ships via Homebrew,
while the hook *scripts* (``hooks/*.sh``) are fetched by pre-commit from the chargate
repo at the pinned ``rev`` — they are not in the installed wheel.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from collections.abc import Callable
from pathlib import Path

from chargate import __version__

Runner = Callable[[list[str]], "subprocess.CompletedProcess[str]"]
Which = Callable[[str], str | None]

# First line of a chargate-managed ~/.pre-commit-config.yaml. We only ever
# overwrite a config that carries this marker (or when --force is given), so a
# hand-maintained config is never silently clobbered.
SENTINEL = "# managed-by: chargate install-hooks"

# git config keys we own.
_HOOKS_PATH_KEY = "core.hooksPath"
_TEMPLATE_DIR_KEY = "init.templateDir"

# git config --unset exits 5 when the key is absent; that is a no-op for us.
_GIT_CONFIG_UNSET_MISSING = 5


class HookInstallError(RuntimeError):
    """A hook (un)install step failed; the message is user-actionable."""


def _default_runner(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, check=False)


def _managed_config(rev: str) -> str:
    return (
        f"{SENTINEL}\n"
        "# Regenerated by `chargate install-hooks`; rerun with --force to overwrite.\n"
        "# Delete the marker line above to make chargate leave this file alone.\n"
        "default_install_hook_types: [pre-commit, pre-push]\n"
        "repos:\n"
        "  - repo: https://github.com/MagmaMoose/chargate\n"
        f"    rev: {rev}\n"
        "    hooks:\n"
        "      - id: actions-pin-sha\n"
        "      - id: conventional-branch-name\n"
    )


class _Paths:
    """Resolved on-disk locations, rooted at ``home`` for testability."""

    def __init__(self, home: Path) -> None:
        self.home = home
        self.config = home / ".pre-commit-config.yaml"
        self.state = home / ".config" / "chargate" / "state.json"
        self.template_dir = home / ".config" / "chargate" / "git-template"
        self.hooks_dir = self.template_dir / "hooks"


def _git_config_get(runner: Runner, key: str) -> str | None:
    proc = runner(["git", "config", "--global", "--get", key])
    if proc.returncode != 0:
        return None
    value = proc.stdout.strip()
    return value or None


def _git_config_set(runner: Runner, key: str, value: str) -> None:
    proc = runner(["git", "config", "--global", key, value])
    if proc.returncode != 0:
        raise HookInstallError(
            f"`git config --global {key} {value}` failed (exit {proc.returncode}): "
            f"{proc.stderr.strip()}"
        )


def _git_config_unset(runner: Runner, key: str) -> None:
    proc = runner(["git", "config", "--global", "--unset", key])
    if proc.returncode not in (0, _GIT_CONFIG_UNSET_MISSING):
        raise HookInstallError(
            f"`git config --global --unset {key}` failed (exit {proc.returncode}): "
            f"{proc.stderr.strip()}"
        )


def install_hooks(
    *,
    force: bool = False,
    home: Path | None = None,
    runner: Runner | None = None,
    which: Which | None = None,
) -> list[str]:
    """Wire chargate's hooks into git globally. Returns user-facing messages.

    Raises :class:`HookInstallError` for setup failures (missing ``pre-commit``,
    a foreign config that would be clobbered without ``force``, or a failing
    subprocess).
    """
    run: Runner = runner or _default_runner
    which_fn: Which = which or shutil.which
    paths = _Paths(home or Path.home())
    rev = f"v{__version__}"

    if which_fn("git") is None:
        raise HookInstallError("`git` is not on PATH; cannot configure global hooks.")
    if which_fn("pre-commit") is None:
        raise HookInstallError(
            "`pre-commit` is not on PATH. Install it first "
            "(`brew install pre-commit` or `pipx install pre-commit`), then rerun."
        )

    messages: list[str] = []

    # 1. Managed global config — never clobber a foreign one without --force.
    if paths.config.exists():
        existing = paths.config.read_text(encoding="utf-8")
        if SENTINEL not in existing and not force:
            raise HookInstallError(
                f"{paths.config} already exists and was not written by chargate. "
                "Refusing to overwrite it; rerun with --force to replace it."
            )
    paths.config.write_text(_managed_config(rev), encoding="utf-8")
    messages.append(f"Wrote managed pre-commit config: {paths.config} (pinned {rev})")

    # 2. Capture the genuine pre-chargate global config once, for uninstall restore.
    prior_hooks_path = _git_config_get(run, _HOOKS_PATH_KEY)
    prior_template_dir = _git_config_get(run, _TEMPLATE_DIR_KEY)
    if not paths.state.exists():
        paths.state.parent.mkdir(parents=True, exist_ok=True)
        paths.state.write_text(
            json.dumps(
                {_HOOKS_PATH_KEY: prior_hooks_path, _TEMPLATE_DIR_KEY: prior_template_dir},
                indent=2,
            ),
            encoding="utf-8",
        )

    # 3. Generate the framework dispatchers into <template>/hooks for both stages.
    paths.template_dir.mkdir(parents=True, exist_ok=True)
    proc = run(
        [
            "pre-commit",
            "init-templatedir",
            str(paths.template_dir),
            "--hook-type",
            "pre-commit",
            "--hook-type",
            "pre-push",
        ]
    )
    if proc.returncode != 0:
        raise HookInstallError(
            f"`pre-commit init-templatedir` failed (exit {proc.returncode}): {proc.stderr.strip()}"
        )

    # 4. Make them active everywhere: hooksPath (retroactive) + templateDir (new clones).
    if prior_hooks_path and prior_hooks_path != str(paths.hooks_dir):
        messages.append(
            f"Repointing {_HOOKS_PATH_KEY}: {prior_hooks_path} -> {paths.hooks_dir}. "
            "Hooks at the old path are no longer active (this disables any non-chargate "
            "global hooks there). Run `chargate uninstall-hooks` to restore."
        )
    _git_config_set(run, _HOOKS_PATH_KEY, str(paths.hooks_dir))
    _git_config_set(run, _TEMPLATE_DIR_KEY, str(paths.template_dir))

    messages.append("Global git hooks installed (pre-commit + pre-push) for all repositories.")
    return messages


def uninstall_hooks(
    *,
    home: Path | None = None,
    runner: Runner | None = None,
) -> list[str]:
    """Revert what :func:`install_hooks` set, touching only chargate-owned config."""
    run: Runner = runner or _default_runner
    paths = _Paths(home or Path.home())

    prior: dict[str, str | None] = {}
    if paths.state.exists():
        try:
            prior = json.loads(paths.state.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            prior = {}

    messages: list[str] = []
    _restore_or_unset(run, _HOOKS_PATH_KEY, str(paths.hooks_dir), prior, messages)
    _restore_or_unset(run, _TEMPLATE_DIR_KEY, str(paths.template_dir), prior, messages)

    # Remove the managed config only if it still carries our marker.
    if paths.config.exists() and SENTINEL in paths.config.read_text(encoding="utf-8"):
        paths.config.unlink()
        messages.append(f"Removed managed pre-commit config: {paths.config}")

    if paths.state.exists():
        paths.state.unlink()

    if not messages:
        messages.append("Nothing to uninstall (no chargate-managed global hooks found).")
    return messages


def _restore_or_unset(
    runner: Runner,
    key: str,
    managed_value: str,
    prior: dict[str, str | None],
    messages: list[str],
) -> None:
    """Revert ``key`` only if it currently holds chargate's managed value."""
    current = _git_config_get(runner, key)
    if current != managed_value:
        # Someone repointed it after us (or it was never ours) — leave it alone.
        return
    restored = prior.get(key)
    if restored:
        _git_config_set(runner, key, restored)
        messages.append(f"Restored {key}: {managed_value} -> {restored}")
    else:
        _git_config_unset(runner, key)
        messages.append(f"Unset {key} (was {managed_value})")
